[JBPM-5544] Added basic text wrapping
ahome-it/lienzo-core pull request #175
Opened 2017-06-23 15:49 UTC by Christopher-Chianelli

Added basic text wrapping support for Text objects. By default, text will not wrap, and will behave as before. To enable text wrapping, call `setWrapBoundaries(BoundingBox box,Layout layout)`, where `box` is the bounding box for the object where the text resides, and `layout` is the the text layout within the BoundingBox. This patch was made for the 2.0.287-RELEASE (since that the one KIE Workbench (https://github.com/kiegroup/kie-wb-common) uses). Feedback appreciated.

2017-06-28 00:04 UTC, romartin requested changes

2017-06-28 00:04 UTC, romartin commented on src/main/java/com/ait/lienzo/client/core/shape/Text.java
> +    public Text setWrapBoundaries(BoundingBox boundaries, LayoutContainer.Layout layout) {
Hey @Christopher-Chianelli , this part should be moved to the `wires` package. The `LayoutContainer` and the `Layout` are specific classes for using in wiires, so from my point of view, the core lienzo shapes should not depend on this.

2017-06-28 00:07 UTC, romartin commented
Hey @Christopher-Chianelli 

That sound good for me, not sure if @SprocketNYC  had some previous idea for this. Just requested a few  changes for the concrete `LayoutContainer/Layout`, which are intended to just reside in wires, so what you think about moving that concrete code from the `Text` class to some other class in wires?

Thanks!

2017-06-28 03:13 UTC, Christopher-Chianelli commented
I might be able to remove the Layout component entirely and just use getTextAlign, since the code for TOP, CENTER and BOTTOM layout appear to be the same. I'll investigate if that the case when I go back to work tomorrow.

2017-06-28 17:23 UTC, romartin commented
sure thanks @Christopher-Chianelli !

2017-06-28 19:10 UTC, Christopher-Chianelli commented
After some investigations (and learning how to make a wires lienzo project), I managed to fix the line vertical placement and remove Layout from text @romartin.

2017-06-29 20:14 UTC, romartin commented
Hey @Christopher-Chianelli , just did a try to your stuff but still not sure how to make it work. Please, I have added a new test class for your stuff [here](https://github.com/romartin/my-lienzo-tests/commit/20812e4748feef34e583b79b6aa7c9c1ae2d7529), can you give it a try and figure out what I'm missing? Not sure if this does not work at 100% yet or I'm missing to do some another call... but if you run that test, will see that the text is not being wrap yet, any ideas? Thanks!

2017-06-30 13:35 UTC, Christopher-Chianelli commented
@romartin do you have spaces in your text? It only does word wrap currently. I could add an enum so the user could choose wrap style (wrap by word, wrap by word but cut if a word span more than a line, wrap by character, no wrap).

2017-06-30 16:28 UTC, romartin commented
@Christopher-Chianelli well tested both Strings - with spaces and with no spaces. Were you able to run the example link I provided? You can reproduce it there, with and without spaces.

2017-06-30 18:18 UTC, Christopher-Chianelli commented
I see what you mean @romartin; the text position isn't getting updated. However, for some reason my demo doesn't have this issue despite having near identical code https://github.com/Christopher-Chianelli/LienzoDemo

2017-06-30 18:20 UTC, Christopher-Chianelli commented
Nvm, found the fix: remove the child, and add it with the layout @romartin.

2017-06-30 18:21 UTC, Christopher-Chianelli commented
(When updating the wrap boundaries)

2017-07-03 23:02 UTC, romartin commented
Hey @Christopher-Chianelli 

Yeah tested your proposed solution and it works fine. It sounds good for me! Good job :) 

On the other hand, I would say we should try to use another approach rather than adding/removing text instances on each resize event handler, because it sounds quite expensive... Would you mind trying to make this work in wires and without adding/removing the text instance? This way we'll have the complete picture for Stunner. So once merging this we have to be sure that text wrapping works just when using the primitive Text type (as you already has done), and works as well with all wires shapes and the wires resize stuff. 

What I would suggest, as this feature is cool and will be hardly used, is to update the current [Lienzo Kitchen Sink](https://github.com/ahome-it/lienzo-ks), for example just updating the "Wires Resize" example, by adding some text that gets wrapped while resizing, even when clicking on the top buttons  for changing the layout. This way will give visibility to that feature and we can always go to the [KS page](https://www.lienzo-core.com/lienzo-ks/#WELCOME) and check whatever we need :), and finally use same/similar code in Stunner as for the KS :) WDYT?

Thanks!!!

2017-07-04 14:32 UTC, Christopher-Chianelli commented
Hey @romartin!

I think the issue is the text shape is changing, and wires probably assume all children shapes don't change on resize. I'll see what I can do.

2017-07-04 18:17 UTC, romartin commented
Thanks @Christopher-Chianelli , lemme know if  I can help :)

2017-07-04 18:47 UTC, Christopher-Chianelli commented
@romartin, I managed to make it work without removing/readding the child. Needed to modify WiresLayoutContainer to listen to changes to its children BoundingBox's attributes (call refresh() on change). Couldn't get Lienzo Kitchen Sink working; it compiles fine, but exposes no web pages for some reason (despite there being an index.html in war). I tested on your demo.

2017-07-04 19:01 UTC, romartin commented
Hey @Christopher-Chianelli , thanks great job! Let's try to finish it with the example on the KS ,that would be great!
Here are my clues for using the KS:

1. Update the `repositories` configuration in `build.gradle` and add `mavenCentral()` - in order to use your local maven repository, which contains your updates.
2.- Run the command `gradle war` - it generates the war artifact in the path `./build/libs/lienzo-ks.war`
3.- Finally just deploy that war in a tomcat7 

Lemme know if that works!

2017-07-04 19:04 UTC, romartin commented
@Christopher-Chianelli  just tested and the latest KS works for me

2017-07-04 19:30 UTC, Christopher-Chianelli commented
@romartin It worked! But correction, you add `mavenLocal()` to use local maven repositories. Unfortunately, I cannot get it to run inside my IDE.

2017-07-04 19:59 UTC, Christopher-Chianelli commented
@romartin  Added text wrap demo to WiresResizeViewComponent. https://github.com/Christopher-Chianelli/lienzo-ks/tree/text-wrap-demo. Need to add mavenLocal() for it to compile until changes are merged.

2017-07-04 20:21 UTC, romartin commented
great job @Christopher-Chianelli , will give this a try in a bit and let you know!! 
BTW I cannot get KS working from the IDE too. Anyway the idea is that KS is gong to be replaced soon, so do not worry too much for now...
Thanks! :)

2017-07-05 00:15 UTC, romartin commented on src/main/java/com/ait/lienzo/client/core/shape/wires/WiresLayoutContainer.java
> +        public Attribute attr;
just minor thing if you have time, if possible here, always better decoupling and immutability... so just `private final `:)

2017-07-05 00:19 UTC, romartin approved these changes
Hey @Christopher-Chianelli , 
It sounds good for me!! Thanks for all updates and good job again :)
Can you please provide a PR for the lienzo-ks stuff too? And if possible, in the Wires Resize example you added the text to wrap, but it overlaps the text for the actual size.Just appending texts or whatever you think would be nice.

So all good for me to merge! 
CC @manstis  @SprocketNYC 

PS: Will check and merge the PR for lienzo-tests once this gets merged.

Thanks guys!

2017-07-05 08:27 UTC, manstis commented
@romartin @Christopher-Chianelli Looks good to me!

2017-07-05 14:05 UTC, Christopher-Chianelli commented on src/main/java/com/ait/lienzo/client/core/shape/wires/WiresLayoutContainer.java
> +        public Attribute attr;
Thanks! I made everything private/final where possible.

2017-07-05 19:46 UTC, romartin approved these changes
all good for me! Thanks @Christopher-Chianelli

2017-07-08 23:11 UTC, merged

2017-07-08 23:54 UTC, SprocketNYC commented
Is it necessary for Text wrap boundaries to be a BoundingBox ??? You only ever use width and set the width attribute, just setting width would be easier

comments????

2017-07-09 00:05 UTC, romartin commented
yeah @SprocketNYC good point, probably not, not really sure, will let @Christopher-Chianelli answer to this :)

2017-07-09 00:08 UTC, SprocketNYC commented
That way it'll be a real "property" and JSON serialized

2017-07-09 00:09 UTC, SprocketNYC commented
it's kind of straddling a limbo zone between state and property

2017-07-09 00:10 UTC, romartin commented
oh sure, good point!! absolutely agree @SprocketNYC . well you just merged this, up to you! I would vote for refactoring this using just a couple of double attributes too :) @Christopher-Chianelli WDYT?
Thanks

2017-07-09 18:23 UTC, Christopher-Chianelli commented
Good point @SprocketNYC! However, I can imagine adding a feature where height is used - auto-sizing text to fit box - but that is a feature not in this pull request. I used `BoundingBox` since the majority of lienzo shapes provides a `getBoundingBox` method, not a getWidth method. Perhaps we can make Text use doubles internally, but allow you to set them either with `setWrapBoundaries(double)` or `setWrapBoundaries(BoundingBox)`. WDYT?